// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./Game.bs.js";
import * as React from "react";

function App(Props) {
  var game = Props.game;
  return React.createElement("div", {
              className: "root"
            }, React.createElement(Game.make, {
                  game: game
                }));
}

var make = App;

export {
  make ,
  
}
/* Game Not a pure module */
