// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Cell(Props) {
  var color = Props.color;
  var onClick = Props.onClick;
  var identifier = color !== undefined ? (
      color ? "black" : "white"
    ) : "";
  return React.createElement("div", {
              className: "cell " + identifier,
              onClick: onClick
            });
}

var make = Cell;

export {
  make ,
  
}
/* react Not a pure module */
