// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Game from "./Game.bs.js";
import * as React from "react";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";

((require('./index.css')));

var game = Game.init([
      {
        name: "White Player",
        color: /* White */0
      },
      {
        name: "Black Player",
        color: /* Black */1
      }
    ]);

ReactDOMRe.renderToElementWithId(React.createElement(App.make, {
          game: game
        }), "root");

export {
  game ,
  
}
/*  Not a pure module */
