// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function bullet(player) {
  var match = player.color;
  if (match) {
    return "•";
  } else {
    return "○";
  }
}

function Player(Props) {
  var player = Props.player;
  var current = Props.current;
  return React.createElement("div", {
              className: "player" + (
                current ? " current" : ""
              )
            }, player.name, " " + bullet(player));
}

var make = Player;

export {
  bullet ,
  make ,
  
}
/* react Not a pure module */
