// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jest from "@glennsl/bs-jest/src/jest.bs.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Board from "../src/Board.bs.js";
import * as React from "react";
import * as Enzyme from "bs-enzyme/src/Enzyme.bs.js";
import * as Enzyme$1 from "enzyme";
import EnzymeAdapterReact from "@wojtekmaj/enzyme-adapter-react-17";

function matrixToCells(matrix) {
  return Board.sortCells($$Array.to_list($$Array.fold_left($$Array.append, [], $$Array.mapi((function (y, row) {
                            return $$Array.mapi((function (x, color) {
                                          return {
                                                  x: x,
                                                  y: y,
                                                  color: color
                                                };
                                        }), row);
                          }), matrix))));
}

var w = /* White */0;

var b = /* Black */1;

Enzyme.configureEnzyme(new EnzymeAdapterReact());

Jest.describe("Board", (function (param) {
        Jest.describe("initCells", (function (param) {
                return Jest.test("it should init a list of cells", (function (param) {
                              return Jest.Expect.toEqual({
                                          hd: {
                                            x: 0,
                                            y: 0,
                                            color: undefined
                                          },
                                          tl: {
                                            hd: {
                                              x: 1,
                                              y: 0,
                                              color: undefined
                                            },
                                            tl: {
                                              hd: {
                                                x: 0,
                                                y: 1,
                                                color: undefined
                                              },
                                              tl: {
                                                hd: {
                                                  x: 1,
                                                  y: 1,
                                                  color: undefined
                                                },
                                                tl: /* [] */0
                                              }
                                            }
                                          }
                                        }, Jest.Expect.expect(Board.initCells(2, 2, undefined)));
                            }));
              }));
        Jest.describe("sortCells", (function (param) {
                return Jest.test("should sort cell by x/y coords", (function (param) {
                              return Jest.Expect.toEqual({
                                          hd: {
                                            x: 1,
                                            y: 0,
                                            color: undefined
                                          },
                                          tl: {
                                            hd: {
                                              x: 2,
                                              y: 0,
                                              color: undefined
                                            },
                                            tl: {
                                              hd: {
                                                x: 1,
                                                y: 1,
                                                color: undefined
                                              },
                                              tl: {
                                                hd: {
                                                  x: 1,
                                                  y: 2,
                                                  color: undefined
                                                },
                                                tl: {
                                                  hd: {
                                                    x: 2,
                                                    y: 2,
                                                    color: undefined
                                                  },
                                                  tl: {
                                                    hd: {
                                                      x: 1,
                                                      y: 3,
                                                      color: undefined
                                                    },
                                                    tl: /* [] */0
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }, Jest.Expect.expect(Board.sortCells({
                                                  hd: {
                                                    x: 1,
                                                    y: 0,
                                                    color: undefined
                                                  },
                                                  tl: {
                                                    hd: {
                                                      x: 1,
                                                      y: 3,
                                                      color: undefined
                                                    },
                                                    tl: {
                                                      hd: {
                                                        x: 2,
                                                        y: 0,
                                                        color: undefined
                                                      },
                                                      tl: {
                                                        hd: {
                                                          x: 1,
                                                          y: 2,
                                                          color: undefined
                                                        },
                                                        tl: {
                                                          hd: {
                                                            x: 1,
                                                            y: 1,
                                                            color: undefined
                                                          },
                                                          tl: {
                                                            hd: {
                                                              x: 2,
                                                              y: 2,
                                                              color: undefined
                                                            },
                                                            tl: /* [] */0
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                })));
                            }));
              }));
        Jest.describe("getCell", (function (param) {
                Jest.test("it should return cell color if exist", (function (param) {
                        return Jest.Expect.toEqual(/* White */0, Jest.Expect.expect(Board.getCell(1, 3, {
                                            hd: {
                                              x: 1,
                                              y: 0,
                                              color: undefined
                                            },
                                            tl: {
                                              hd: {
                                                x: 2,
                                                y: 0,
                                                color: undefined
                                              },
                                              tl: {
                                                hd: {
                                                  x: 1,
                                                  y: 1,
                                                  color: undefined
                                                },
                                                tl: {
                                                  hd: {
                                                    x: 1,
                                                    y: 2,
                                                    color: undefined
                                                  },
                                                  tl: {
                                                    hd: {
                                                      x: 2,
                                                      y: 2,
                                                      color: undefined
                                                    },
                                                    tl: {
                                                      hd: {
                                                        x: 1,
                                                        y: 3,
                                                        color: /* White */0
                                                      },
                                                      tl: /* [] */0
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          })));
                      }));
                return Jest.test("it should return None if cell does not exist", (function (param) {
                              return Jest.Expect.toEqual(undefined, Jest.Expect.expect(Board.getCell(1, 4, {
                                                  hd: {
                                                    x: 1,
                                                    y: 0,
                                                    color: undefined
                                                  },
                                                  tl: {
                                                    hd: {
                                                      x: 1,
                                                      y: 2,
                                                      color: undefined
                                                    },
                                                    tl: {
                                                      hd: {
                                                        x: 2,
                                                        y: 2,
                                                        color: undefined
                                                      },
                                                      tl: {
                                                        hd: {
                                                          x: 1,
                                                          y: 3,
                                                          color: /* White */0
                                                        },
                                                        tl: /* [] */0
                                                      }
                                                    }
                                                  }
                                                })));
                            }));
              }));
        Jest.describe("init", (function (param) {
                return Jest.test("should return a new board", (function (param) {
                              return Jest.Expect.toEqual({
                                          width: 4,
                                          height: 4,
                                          cells: matrixToCells([
                                                [
                                                  undefined,
                                                  undefined,
                                                  undefined,
                                                  undefined
                                                ],
                                                [
                                                  undefined,
                                                  b,
                                                  w,
                                                  undefined
                                                ],
                                                [
                                                  undefined,
                                                  w,
                                                  b,
                                                  undefined
                                                ],
                                                [
                                                  undefined,
                                                  undefined,
                                                  undefined,
                                                  undefined
                                                ]
                                              ])
                                        }, Jest.Expect.expect(Board.init(4, 4)));
                            }));
              }));
        Jest.describe("drawCells", (function (param) {
                return Jest.test("should return a new board with new cells", (function (param) {
                              return Jest.Expect.toEqual(matrixToCells([
                                              [
                                                b,
                                                undefined
                                              ],
                                              [
                                                undefined,
                                                w
                                              ]
                                            ]), Jest.Expect.expect(Board.drawCells(matrixToCells([
                                                      [
                                                        undefined,
                                                        undefined
                                                      ],
                                                      [
                                                        undefined,
                                                        undefined
                                                      ]
                                                    ]), {
                                                  hd: {
                                                    x: 0,
                                                    y: 0,
                                                    color: /* Black */1
                                                  },
                                                  tl: {
                                                    hd: {
                                                      x: 1,
                                                      y: 1,
                                                      color: /* White */0
                                                    },
                                                    tl: /* [] */0
                                                  }
                                                })));
                            }));
              }));
        Jest.describe("getCountForColor", (function (param) {
                return Jest.test("should return the number of cells of corresponding color", (function (param) {
                              Jest.Expect.toBe(2, Jest.Expect.expect(Board.getCountForColor(Board.init(4, 4), /* Black */1)));
                              Jest.Expect.toBe(2, Jest.Expect.expect(Board.getCountForColor(Board.init(4, 4), /* White */0)));
                              return Jest.Expect.toBe(12, Jest.Expect.expect(Board.getCountForColor(Board.init(4, 4), undefined)));
                            }));
              }));
        Jest.describe("isOutOfBound", (function (param) {
                var baseBoard = Board.init(4, 4);
                Jest.test("should return true for out of bounds coords", (function (param) {
                        Jest.Expect.toBe(true, Jest.Expect.expect(Board.isOutOfBound(baseBoard, [
                                      3,
                                      4
                                    ])));
                        Jest.Expect.toBe(true, Jest.Expect.expect(Board.isOutOfBound(baseBoard, [
                                      4,
                                      3
                                    ])));
                        Jest.Expect.toBe(true, Jest.Expect.expect(Board.isOutOfBound(baseBoard, [
                                      -1,
                                      0
                                    ])));
                        return Jest.Expect.toBe(true, Jest.Expect.expect(Board.isOutOfBound(baseBoard, [
                                            0,
                                            -1
                                          ])));
                      }));
                return Jest.test("should return false for inner bounds coords", (function (param) {
                              Jest.Expect.toBe(false, Jest.Expect.expect(Board.isOutOfBound(baseBoard, [
                                            0,
                                            0
                                          ])));
                              Jest.Expect.toBe(false, Jest.Expect.expect(Board.isOutOfBound(baseBoard, [
                                            3,
                                            3
                                          ])));
                              return Jest.Expect.toBe(false, Jest.Expect.expect(Board.isOutOfBound(baseBoard, [
                                                  1,
                                                  3
                                                ])));
                            }));
              }));
        Jest.describe("flippedCellsInDirection", (function (param) {
                var baseBoard = Board.init(4, 4);
                Jest.test("should return empty list for an out of bounds cell change", (function (param) {
                        return Jest.Expect.toBe(/* [] */0, Jest.Expect.expect(Board.flippedCellsInDirection(baseBoard, {
                                            x: -1,
                                            y: 0,
                                            color: /* Black */1
                                          }, [
                                            1,
                                            1
                                          ])));
                      }));
                Jest.test("should return empty list for an empty cell in direction", (function (param) {
                        return Jest.Expect.toBe(/* [] */0, Jest.Expect.expect(Board.flippedCellsInDirection(baseBoard, {
                                            x: 0,
                                            y: 0,
                                            color: /* Black */1
                                          }, [
                                            1,
                                            0
                                          ])));
                      }));
                Jest.test("should return empty list for a same cell color next to cell change", (function (param) {
                        return Jest.Expect.toBe(/* [] */0, Jest.Expect.expect(Board.flippedCellsInDirection(baseBoard, {
                                            x: 1,
                                            y: 0,
                                            color: /* Black */1
                                          }, [
                                            0,
                                            1
                                          ])));
                      }));
                return Jest.test("should return a filled list for a valid cell change", (function (param) {
                              return Jest.Expect.toEqual({
                                          hd: {
                                            x: 1,
                                            y: 1,
                                            color: /* White */0
                                          },
                                          tl: /* [] */0
                                        }, Jest.Expect.expect(Board.flippedCellsInDirection(baseBoard, {
                                                  x: 1,
                                                  y: 0,
                                                  color: /* White */0
                                                }, [
                                                  0,
                                                  1
                                                ])));
                            }));
              }));
        Jest.describe("getFlippedCells", (function (param) {
                var fakeBoard_cells = matrixToCells([
                      [
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined
                      ],
                      [
                        undefined,
                        b,
                        undefined,
                        undefined,
                        undefined,
                        undefined
                      ],
                      [
                        undefined,
                        w,
                        w,
                        w,
                        undefined,
                        undefined
                      ],
                      [
                        undefined,
                        undefined,
                        w,
                        b,
                        undefined,
                        undefined
                      ],
                      [
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined
                      ],
                      [
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined
                      ]
                    ]);
                var fakeBoard = {
                  width: 6,
                  height: 6,
                  cells: fakeBoard_cells
                };
                return Jest.test("should return flipped cells from cell change in all directions", (function (param) {
                              return Jest.Expect.toEqual({
                                          hd: {
                                            x: 1,
                                            y: 3,
                                            color: /* Black */1
                                          },
                                          tl: {
                                            hd: {
                                              x: 1,
                                              y: 2,
                                              color: /* Black */1
                                            },
                                            tl: {
                                              hd: {
                                                x: 2,
                                                y: 3,
                                                color: /* Black */1
                                              },
                                              tl: /* [] */0
                                            }
                                          }
                                        }, Jest.Expect.expect(Board.getFlippedCells(fakeBoard, {
                                                  x: 1,
                                                  y: 3,
                                                  color: /* Black */1
                                                })));
                            }));
              }));
        Jest.describe("availableCellChanges", (function (param) {
                return Jest.test("should return all available cell changes for a color", (function (param) {
                              return Jest.Expect.toEqual({
                                          hd: {
                                            x: 2,
                                            y: 0,
                                            color: /* Black */1
                                          },
                                          tl: {
                                            hd: {
                                              x: 3,
                                              y: 1,
                                              color: /* Black */1
                                            },
                                            tl: {
                                              hd: {
                                                x: 0,
                                                y: 2,
                                                color: /* Black */1
                                              },
                                              tl: {
                                                hd: {
                                                  x: 1,
                                                  y: 3,
                                                  color: /* Black */1
                                                },
                                                tl: /* [] */0
                                              }
                                            }
                                          }
                                        }, Jest.Expect.expect(Board.availableCellChanges(Board.init(4, 4), /* Black */1)));
                            }));
              }));
        Jest.describe("applyCellChange", (function (param) {
                var fakeBoard = Board.init(4, 4);
                Jest.test("should raise an InvalidMove if cell change target is not empty", (function (param) {
                        return Jest.Expect.toThrow(Jest.Expect.expect(function (param) {
                                        return Board.applyCellChange(fakeBoard, {
                                                    x: 1,
                                                    y: 1,
                                                    color: /* White */0
                                                  });
                                      }));
                      }));
                Jest.test("should raise an InvalidMove if cell change does not flip any cell", (function (param) {
                        return Jest.Expect.toThrow(Jest.Expect.expect(function (param) {
                                        return Board.applyCellChange(fakeBoard, {
                                                    x: 0,
                                                    y: 0,
                                                    color: /* White */0
                                                  });
                                      }));
                      }));
                return Jest.test("should return an updated board if cell change is valid", (function (param) {
                              return Jest.Expect.toEqual({
                                          width: 4,
                                          height: 4,
                                          cells: matrixToCells([
                                                [
                                                  undefined,
                                                  w,
                                                  undefined,
                                                  undefined
                                                ],
                                                [
                                                  undefined,
                                                  w,
                                                  w,
                                                  undefined
                                                ],
                                                [
                                                  undefined,
                                                  w,
                                                  b,
                                                  undefined
                                                ],
                                                [
                                                  undefined,
                                                  undefined,
                                                  undefined,
                                                  undefined
                                                ]
                                              ])
                                        }, Jest.Expect.expect(Board.applyCellChange(fakeBoard, {
                                                  x: 1,
                                                  y: 0,
                                                  color: /* White */0
                                                })));
                            }));
              }));
        return Jest.describe("<Board />", (function (param) {
                      return Jest.test("should render a grid of <Cell />", (function (param) {
                                    var board = Board.init(4, 4);
                                    var wrapper = Enzyme$1.shallow(React.createElement(Board.make, {
                                              board: board,
                                              onCellClick: (function (param) {
                                                  
                                                })
                                            }));
                                    return Jest.Expect.toBe(16, Jest.Expect.expect(wrapper.find("Cell").length));
                                  }));
                    }));
      }));

var n;

export {
  matrixToCells ,
  w ,
  b ,
  n ,
  
}
/*  Not a pure module */
