// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cell from "../src/Cell.bs.js";
import * as Jest from "@glennsl/bs-jest/src/jest.bs.js";
import * as React from "react";
import * as Enzyme from "../src/Enzyme.bs.js";
import * as Enzyme$1 from "enzyme";
import EnzymeAdapterReact from "@wojtekmaj/enzyme-adapter-react-17";

Enzyme.configureEnzyme(new EnzymeAdapterReact());

Jest.describe("<Cell />", (function (param) {
        return Jest.test("should render a disk with the right identifier", (function (param) {
                      var test = function (color, expectedClass) {
                        var wrapper = Enzyme$1.shallow(React.createElement(Cell.make, {
                                  color: color,
                                  onClick: (function (param) {
                                      
                                    })
                                }));
                        return Jest.Expect.toBe(1, Jest.Expect.expect(wrapper.find(expectedClass).length));
                      };
                      test(/* Black */1, ".cell.black");
                      test(/* White */0, ".cell.white");
                      return test(undefined, ".cell");
                    }));
      }));

export {
  
}
/*  Not a pure module */
